service: graphql-yoga-boilerplate

package:
  include:
    - src/**/*.graphql

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10

functions:
  graphql:
    handler: src/lambda.server
    events:
      - http:
          path: /
          method: post
          cors: true

  playground:
    handler: src/lambda.playground
    events:
      - http:
          path: /
          method: get
          cors: true
